### ISSUE TITLE
命令行提交了以后没报错，网页也提示成功，但是进草稿箱看不到

### ISSUE THREAD

**Issue by Zacharia2** [zihengCat/bilibili-zhuanlan-markdown-tool#12]
> bilibili-zhuanlan-markdown-tool@1.0.8 cli C:\Users\Mxun\Desktop\bilibili-zhuanlan-markdown-tool
> node dist/BiliColumnCLI.js "C:\Users\Mxun\Desktop\【学习】英语语法\高中语法.md"

[INFO]: Sending Markdown files to Bilibili server...

操作完成后B站草稿箱没有更新，已提前创建草稿并保存。

**Comment by Zacharia2** [comment]
我觉得应该是文字超过20000字限制

**Comment by zihengCat** [comment]
@Zacharia2 样例 Markdown 文稿发下，我看看。
