### ISSUE TITLE
用的网页提交成功，但是进草稿箱看不到，还是和原来一样

### ISSUE THREAD

**Issue by youaremyall** [zihengCat/bilibili-zhuanlan-markdown-tool#13]

**Comment by zihengCat** [comment]
麻烦提供下详细信息。 @youaremyall 
- 操作系统
- Node.js 版本
- 样例 Markdown 文档

**Comment by youaremyall** [comment]
MAC系统&nbsp;&nbsp;
版本 6.3.1






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ziheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 下午2:03
收件人:&nbsp;"zihengCat/bilibili-zhuanlan-markdown-tool"<bilibili-zhuanlan-markdown-tool@noreply.github.com&gt;;
抄送:&nbsp;"491964334"<491964334@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zihengCat/bilibili-zhuanlan-markdown-tool] 用的网页提交成功，但是进草稿箱看不到，还是和原来一样 (#13)



 麻烦提供下详细信息。 @youaremyall
  操作系统
 Node.js 版本
 样例 Markdown 文档

**Comment by zihengCat** [comment]
@youaremyall 
我这边本机测试没啥问题...
你换命令行提交，看下命令行打印的日志信息。

**Comment by zihengCat** [comment]
@youaremyall 
可以的话，把样例 Markdown 文档附件发我邮箱。
> zihenglv@gmail.com

**Comment by zihengCat** [comment]
@youaremyall 
问题原因找到了，B 站专栏后端又加强了外链屏蔽规则，你的 Markdown 文档带图片外链，提交不上去。
![Screen Shot 2020-06-01 at 15 09 08](https://user-images.githubusercontent.com/19472493/83384440-de5d1000-a419-11ea-8bb9-fb34b1422442.png)
![Screen Shot 2020-06-01 at 15 08 59](https://user-images.githubusercontent.com/19472493/83384448-e1f09700-a419-11ea-976b-160ad4cea0be.png)

**Comment by youaremyall** [comment]
好的 谢谢 那只有上传B站的图片链接才可以？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ziheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 下午3:14
收件人:&nbsp;"zihengCat/bilibili-zhuanlan-markdown-tool"<bilibili-zhuanlan-markdown-tool@noreply.github.com&gt;;
抄送:&nbsp;"491964334"<491964334@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [zihengCat/bilibili-zhuanlan-markdown-tool] 用的网页提交成功，但是进草稿箱看不到，还是和原来一样 (#13)



 @youaremyall
 问题原因找到了，B 站专栏后端又加强了外链屏蔽规则，你的 Markdown 文档带图片外链，提交不上去。

**Comment by zihengCat** [comment]
@youaremyall 

**把外链图片换成本地图片：**

1. 下载图片到本地。
2. Markdown 文档写图片相对地址。
3. 提交，该工具自动上传图片到 B 站。

> `![alt](./xxx.jpg)`
<img width="1136" alt="Screen Shot 2020-06-01 at 15 17 04" src="https://user-images.githubusercontent.com/19472493/83385160-537d1500-a41b-11ea-958a-d92dcf508bf1.png">
