### ISSUE TITLE
提交一次之后后续的提交就无效了？

### ISSUE THREAD

**Issue by qiudaozhang** [zihengCat/bilibili-zhuanlan-markdown-tool#6]
第一次测试提交通过，第二次测试提交就无效了。

**Comment by zihengCat** [comment]
麻烦描述下问题详细情况。
@qiudaozhang

**Comment by zero-cooper** [comment]
应该是里面有bug，对于多次提交，每一次提交成功的aid值会变化，对于一个同样的草稿；在反馈输出的正常提交信息里面也可以看出来；以下是我多次成功提交后的输出信息：

PS D:\bilibili-zhuanlan-markdown-tool-master> node src/cli.js docs/pmr1.md
StatusCode:  200
Data: {"code":0,"message":"0","ttl":1,"data":{"aid":29775}}
PS D:\bilibili-zhuanlan-markdown-tool-master> node src/cli.js docs/pmr1.md
StatusCode:  200
Data: {"code":0,"message":"0","ttl":1,"data":{"aid":29776}}
PS D:\bilibili-zhuanlan-markdown-tool-master> node src/cli.js docs/pmr1.md
StatusCode:  200
Data: {"code":0,"message":"0","ttl":1,"data":{"aid":29777}}
PS D:\bilibili-zhuanlan-markdown-tool-master> node src/cli.js docs/pmr1.md
StatusCode:  200
Data: {"code":0,"message":"0","ttl":1,"data":{"aid":29778}}
PS D:\bilibili-zhuanlan-markdown-tool-master> node src/cli.js docs/pmr1.md
StatusCode:  200
Data: {"code":0,"message":"0","ttl":1,"data":{"aid":29779}}
PS D:\bilibili-zhuanlan-markdown-tool-master>

应该是每次程序改变了aid值导致没有上传到应有的你的草稿里（我的草稿aid=29769）；望解决。
