### ISSUE TITLE
latex in markdown

### ISSUE THREAD

**Issue by zero-cooper** [zihengCat/bilibili-zhuanlan-markdown-tool#7]
markdown 中的latex表示的数学符号公式有办法渲染吗？

**Comment by zihengCat** [comment]
@zero-cooper 
暂时还没有很好的解决办法，B站不支持 LaTeX 渲染。
替代方案：使用图片替换 Markdown 中的 LaTeX 公式，比较麻烦...
> http://latex2png.com/
